version: '3'

services:
  db:
    #image: postgres:9.6
    build:
      context: .
      dockerfile: Dockerfile-db

    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_DB=jeugdzorg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=jeugdzorg

  dbadmin:
    image: fenglc/pgadmin4
    environment:
      - POSTGRES_DB=jeugdzorg
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD=postgres
    ports:
      - "5050:5050"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    restart: always
    volumes:
      - ./jeugdzorg:/opt/app
      - ./media:/opt/file_upload
    environment:
      - ENV=develop
      - DJANGO_ENV=dev
      - RUNSERVER=yes
      - POSTGRES_DB=jeugdzorg
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ADMIN_USERNAME=dj_username
      - ADMIN_PASSWORD=dj_password
      - ADMIN_EMAIL=username@host.nl
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  pg_data: {}
  pg_backups: {}